<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
<style type="text/css">
<!--
body,td,th {
	font-family: Geneva, Arial, Helvetica, sans-serif;
	font-size: 14px;
}
body {
	background-color: #FFFFFF;
	margin-left: 0px;
	margin-top: 0px;
	margin-right: 0px;
	margin-bottom: 0px;
}
.style1 {
	font-size: 18px;
	font-weight: bold;
	color: #FFFFFF;
}
.style2 {
	color: #9FCC3C;
	font-weight: bold;
	font-size: 16px;
}
.style3 {color: #F68428}
.style4 {color: #0076BE}
.style6 {font-size: 36px; font-weight: bold; color: #FFFFFF; }
-->
</style>






</head>

<body>
<div>
<p>Dear <?=ucfirst($name)?>,</p>
<p>The New Demo password as generated by Eduzyte is <b><?=$password?></b> . </p>
<p>Please note, after login please update your password.</p>
<p>Please do not share this  Password with anyone.</p>
<!--<p>To know more, refer to</p>
<p>In case you have not requested for OTP, please contact the Eduzyte helpline at +91 63 03 145 155.</p>-->
<br>
<p>Warm Regards</p>
<p>EduzytE.com<p>  
</div>
</body>
</html>